### ISSUE TITLE
Add better support for dates in queries

### ISSUE THREAD

**Issue by habbes** [alphamanuscript/surix-js-sdk#23]
Because JSON has not native encoding for dates, the API provides special syntax for dates in queries. If you just naively convert dates to their string representation (which I assume is what's currently happening), the query will treat strings and that my return unexpected results.

## Background

The API provides the `$treatAsDatetime` modifier, which lets you tell the query that you want a certain value to be treated as a `Date` object, and not a string. Here's how you'd use it in a query:

```javascript
{
   query: {
      birthDate : { $treatAsDatetime: '2019-03-01' }
   }
}

```

The value passed as the value to the `$treatAsDatetime` key is any string or number that can be passed as the single argument to the `Date` constructor (i.e. that value will be as `new Date(value)`).

You can also use this technique with comparison operators:

```javascript
{
  query: {
    birthDate: { $lte: { $treatAsDatetime: '2019-03-01' } }
  }
}
```

as well as conditional operators:

```javascript
{
   query: {
      $or: [
          { city: 'Nairobi' },
          { birthDate: { $not: { $treatAsDatetime: '2019-03-01' } }
      ]
  }
}
```

## What to implement

The user of the library does not have to deal with these intricacies, they should be able to use Javascript `Date` objects (created using `new Date()`)  in the query passed to `project.entities.query()`. Then you should traverse the query object, transforming instances of the `Date` object to `$treatAsDatetime` directives before sending them to the API.

**Comment by habbes** [comment]
So here are basics about query syntax.
The query object passed to `project.entities.query` looks like:
```js
{ 
   query: { amount: { $gt: 100 } },
   limit: 100,
   skip: 0,
   tagsAll: ['tag1', 'tag2'],
   tagsNone: ['tag1', 'tag2'],
   tagsSome: ['tag1', 'tag2']
}
```
Each of those fields are optional. Furthermore, `tagsAll`, `tagsNone` and `tagsSome` are mutually exclusive. But what we're concerned with is the `query` property, which contain the filters. So let's dig deeper into that.

### Query filters

At the most basic, the query object is mapping between field names (or nested field paths) and a filter match condition. The condition could be:

#### Simple value matches

in which case the db will check whether the field equals that value:

```
{
   query: {
      amount: 100,
      'address.city': 'Nairobi'
   }
}
```

#### Comparison operators

in each case the field is mapped to an object which contains the comparison operator as the key and the value being compared as the value:
```js
{
   query: {
      amount: { $gt: 100 },
      'address.city': { $ne: 'Nairobi' }
  }
}
```
Supported operators are `$eq`, `$ne`, `$gt`, `$gte`, `$lt`, `$lte`

#### Date support

To pass date values to the API query, use the following syntax `{ $treatAsDatetime: 'date string' }` or `{ $treatAsDatetime: timestampMilliseconds }`

e.g:
```js
{
   query: {
     purchaseDate: { $gte: { $treatAsDatetime: '2019-04-21' }
   }
}
```

```js
{
   query: {
     purchaseDate: { $treatAsDatetime: 3242324324 }
   }
}
```

Note that the `$treatAsDatetime` object can be used anywhere a value is expected, i.e. it can be used as the operand of a comparison operator, or it can be used as the direct value match of the field.

But of course we want to abstract this syntax away from SDK users, and just allow them to use date objects, like:

```js
{  query: { purchaseDate: { $gte: new Date() } } }
```
or
```js
{ query: { purchaseDate: new Date() } }
```

And that is the essence of this task.

#### Regex support

The API also has a special syntax for regex values

```js
{
   query: {
      name: { $regex: 'string' }
   }
}
```
The `$regex` keyword behaves like comparison operator. It cannot be used with other comparison ops, e.g. you cannot do this:
```js
{
 query: {
   name: {
     $gte: { $regex: 'string' }
   }
}
```

The `$regex` operator also takes options like:
```js
{
   query: {
     name: { $regex: 'string', $options: 'i' } // use case-insensitive mode
   }
}
```

**Comment by habbes** [comment]
I think an easy to implement this is to recursively traverse the query object, and when you encounter a Date value, you replace it with `{ $treatAsDatetime: date.getTime() }` or `{ $treatAsDatetime: date.toISOString() }`, and if the object is an array (like in the case of `$or`), you iterate of each object, and recursively traverse them.

**Comment by grafitto** [comment]
Nice. Understood

**Comment by grafitto** [comment]
Will now include the changes in #27 onto the client
