### ISSUE TITLE
API Library doesn't work in Node.js

### ISSUE THREAD

**Issue by habbes** [alphamanuscript/surix-js-sdk#6]

**Comment by grafitto** [comment]
tests have proved that this is no longer an issue and the library works as expected in browsers, Mode.js and TypeScript
![browser](https://user-images.githubusercontent.com/8601175/59127959-8eb44780-8971-11e9-9729-e1654abf5d1e.png)
![js](https://user-images.githubusercontent.com/8601175/59127966-94119200-8971-11e9-8b7d-f3acfb2eea7c.png)
![typescript](https://user-images.githubusercontent.com/8601175/59127969-9673ec00-8971-11e9-8849-1722d3e2320f.png)
